config/routes.rb
Msza::Application.routes.draw do

  resources :terminy

  resources :kraje

  resources :miejsca

  resources :osoby

  root :to => 'miejsca#index'

  match "login" => "sessions#new"
  match "loguj" => "sessions#new"
  match "wyloguj" => "sessions#destroy"

  match 'reset_hasla' => 'osoby#reset_hasla', :via => :get
  match 'reset_hasla' => 'osoby#zresetuj_haslo', :via => :post
  match 'ustaw_haslo' => 'osoby#ustaw_haslo', :via => :get
 

  scope(:path_names=>{:new=>"nowa", :edit=>"edytuj"}) do
    resources :grupy, :osoby, :aktualnosci
    resources :sessions, :path=>"sesje"
  end

end

app/controllers/terminy_controller.rb
class TerminyController < ApplicationController
  load_and_authorize_resource
  # GET /terminy
  # GET /terminy.json
  def index
    @terminy = Termin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @terminy }
    end
  end

  # GET /terminy/1
  # GET /terminy/1.json
  def show
    @termin = Termin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @termin }
    end
  end

  # GET /terminy/new
  # GET /terminy/new.json
  def new
    @termin = Termin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @termin }
    end
  end

  # GET /terminy/1/edit
  def edit
    @termin = Termin.find(params[:id])
  end

  # POST /terminy
  # POST /terminy.json
  def create
    @termin = Termin.new(params[:termin])

    respond_to do |format|
      if @termin.save
        format.html { redirect_to @termin, notice: 'Termin was successfully created.' }
        format.json { render json: @termin, status: :created, location: @termin }
      else
        format.html { render action: "new" }
        format.json { render json: @termin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /terminy/1
  # PUT /terminy/1.json
  def update
    @termin = Termin.find(params[:id])

    respond_to do |format|
      if @termin.update_attributes(params[:termin])
        format.html { redirect_to @termin, notice: 'Termin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @termin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terminy/1
  # DELETE /terminy/1.json
  def destroy
    @termin = Termin.find(params[:id])
    @termin.destroy

    respond_to do |format|
      format.html { redirect_to terminy_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/terminy_helper.rb
module TerminyHelper
end

app/views/terminy/_form.html.erb
<%= form_for(@termin) do |f| %>
  <% if @termin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@termin.errors.count, "error") %> prohibited this termin from being saved:</h2>

      <ul>
      <% @termin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dzien %><br />
    <%= f.text_field :dzien %>
  </div>
  <div class="field">
    <%= f.label :godzina %><br />
    <%= f.text_field :godzina %>
  </div>
  <div class="field">
    <%= f.label :komentarz %><br />
    <%= f.text_field :komentarz %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terminy/_termin_fields_table.html.erb
<tr>
  <td>
   <%= f.hidden_field :id  %>
  </td>
  <td>
   <%= f.select :dzien_id, options_for_select(Dzien.order(:id).map{|d| [d.nazwa,d.id]},f.object.dzien_id), {:include_blank=>true}, :class=>'span2'  %>
  </td>
  <td>
    <%=f.text_field :godzina%>
  </td>
  <td>
    <%=f.text_field :komentarz%>
  </td>
  <td>
    <%=link_to_remove_fields 'tr', '- usuń termin'%>
  </td>
</tr>

app/views/terminy/edit.html.erb
<h1>Editing termin</h1>

<%= render 'form' %>

<%= link_to 'Show', @termin %> |
<%= link_to 'Back', terminy_path %>

app/views/terminy/index.html.erb
<h1>Listing terminy</h1>

<table>
  <tr>
    <th>Dzien</th>
    <th>Godzina</th>
    <th>Komentarz</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @terminy.each do |termin| %>
  <tr>
    <td><%= termin.dzien %></td>
    <td><%= termin.godzina %></td>
    <td><%= termin.komentarz %></td>
    <td><%= link_to 'Show', termin %></td>
    <td><%= link_to 'Edit', edit_termin_path(termin) %></td>
    <td><%= link_to 'Destroy', termin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Termin', new_termin_path %>

app/views/terminy/new.html.erb
<h1>New termin</h1>

<%= render 'form' %>

<%= link_to 'Back', terminy_path %>

app/views/terminy/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Dzien:</b>
  <%= @termin.dzien %>
</p>

<p>
  <b>Godzina:</b>
  <%= @termin.godzina %>
</p>

<p>
  <b>Komentarz:</b>
  <%= @termin.komentarz %>
</p>


<%= link_to 'Edit', edit_termin_path(@termin) %> |
<%= link_to 'Back', terminy_path %>