config/routes.rb
Msza::Application.routes.draw do

  resources :terminy

  resources :kraje

  resources :miejsca

  resources :osoby

  root :to => 'miejsca#index'

  match "login" => "sessions#new"
  match "loguj" => "sessions#new"
  match "wyloguj" => "sessions#destroy"

  match 'reset_hasla' => 'osoby#reset_hasla', :via => :get
  match 'reset_hasla' => 'osoby#zresetuj_haslo', :via => :post
  match 'ustaw_haslo' => 'osoby#ustaw_haslo', :via => :get
 

  scope(:path_names=>{:new=>"nowa", :edit=>"edytuj"}) do
    resources :grupy, :osoby, :aktualnosci
    resources :sessions, :path=>"sesje"
  end

end

app/controllers/kraje_controller.rb
class KrajeController < ApplicationController
  load_and_authorize_resource
  # GET /kraje
  # GET /kraje.json
  def index
    @kraje = Kraj.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kraje }
    end
  end

  # GET /kraje/1
  # GET /kraje/1.json
  def show
    @kraj = Kraj.includes(:miejsca=>[{:terminy=>:dzien},:grupy,:kraj]).find(params[:id])
		@miejsca = params[:dzien]? Miejsce.w_dniu_dla_kraju(params[:dzien],@kraj) : Miejsce.where(:kraj_id=>params[:id]).order("nazwa").includes(:kraj ,:grupy,:terminy=>[:dzien])
    @json = @miejsca.to_gmaps4rails do |miejsce, marker|
      marker.infowindow render_to_string(:partial => "miejsca/info_window", :object => miejsce)
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kraj }
    end
  end

  # GET /kraje/new
  # GET /kraje/new.json
  def new
    @kraj = Kraj.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kraj }
    end
  end

  # GET /kraje/1/edit
  def edit
    @kraj = Kraj.find(params[:id])
  end

  # POST /kraje
  # POST /kraje.json
  def create
    @kraj = Kraj.new(params[:kraj])

    respond_to do |format|
      if @kraj.save
        format.html { redirect_to @kraj, notice: 'Kraj was successfully created.' }
        format.json { render json: @kraj, status: :created, location: @kraj }
      else
        format.html { render action: "new" }
        format.json { render json: @kraj.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kraje/1
  # PUT /kraje/1.json
  def update
    @kraj = Kraj.find(params[:id])

    respond_to do |format|
      if @kraj.update_attributes(params[:kraj])
        format.html { redirect_to @kraj, notice: 'Kraj was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kraj.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kraje/1
  # DELETE /kraje/1.json
  def destroy
    @kraj = Kraj.find(params[:id])
    @kraj.destroy

    respond_to do |format|
      format.html { redirect_to kraje_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kraje_helper.rb
module KrajeHelper
end

app/views/kraje/_form.html.erb
<%= form_for(@kraj) do |f| %>
  <% if @kraj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kraj.errors.count, "error") %> prohibited this kraj from being saved:</h2>

      <ul>
      <% @kraj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br />
    <%= f.text_field :nazwa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kraje/_kraj.html.erb
<h3><%=link_to kraj.nazwa,kraj%></h3>
<table  class="table table-striped">
  <tr>
    <th>Miejsce</th>
    <th>Adres</th>
    <th>Godziny</th>
    <th></th>

  </tr>

	<% kraj.miejsca.each do |miejsce| %>
  <tr>
    <td><%=link_to miejsce.nazwa,miejsce %></td>
    <td><%= miejsce.ulica %>, <%=miejsce.kod%> <%=miejsce.miasto%></td>
    <td>
       <%miejsce.terminy.each do |t|%>
          <%= t.try(:dzien).try(:nazwa) %>: <%=t.godzina%>
          <%=", " if t!=miejsce.terminy.last%>
       <%end%>
    </td>
    <td><%=link_to "Pokaż",miejsce %></td>
    <%if can? :edit, miejsce%>
    <td><%= link_to 'Edit', edit_miejsce_path(miejsce) %></td>
    <td><%= link_to 'Destroy', miejsce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <%end%>
  </tr>
<% end %>
</table>

app/views/kraje/edit.html.erb
<h1>Editing kraj</h1>

<%= render 'form' %>

<%= link_to 'Show', @kraj %> |
<%= link_to 'Back', kraje_path %>

app/views/kraje/index.html.erb
<h1>Listing kraje</h1>

<table>
  <tr>
    <th>Nazwa</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kraje.each do |kraj| %>
  <tr>
    <td><%= kraj.nazwa %></td>
    <td><%= link_to 'Show', kraj %></td>
    <td><%= link_to 'Edit', edit_kraj_path(kraj) %></td>
    <td><%= link_to 'Destroy', kraj, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kraj', new_kraj_path %>

app/views/kraje/new.html.erb
<h1>New kraj</h1>

<%= render 'form' %>

<%= link_to 'Back', kraje_path %>

app/views/kraje/show.html.erb
<p id="notice"><%= notice %></p>
<h2>
  <%= @kraj.nazwa %>
</h2>
<h3>
  Msze Trydenckie
</h3>
<%= render "layouts/dni",:kontroler=>"kraje",:akcja=>"show",:id=>@kraj.id %>

<%= gmaps(:map_options => {  :auto_adjust => false,:zoom=>5}, :markers => {:data => @json,:options => { :do_clustering => true}}) %>
<%#= gmaps4rails(@json) %>

<%#=form_tag do%>
  <%#= text_field_tag :user_address %>
<%#end%>

<% content_for :scripts do %>
  <script type="text/javascript" charset="utf-8">
   Gmaps.map.callback = function() {

      var input = document.getElementById('user_address');
      var country = "<%=@kraj.nazwa%>";
      var geocoder=new google.maps.Geocoder();;

      geocoder.geocode( {'address' : country}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          Gmaps.map.serviceObject.setCenter(results[0].geometry.location);
          Gmaps.map.serviceObject.fitBounds(results[0].geometry.viewport);
        }
      });
    }
  </script>
<%end%>
<%= render @kraj %>

<%= link_to 'Edit', edit_kraj_path(@kraj) %> |
<%= link_to 'Back', kraje_path %>