config/routes.rb
Msza::Application.routes.draw do

  resources :terminy

  resources :kraje

  resources :miejsca

  resources :osoby

  root :to => 'miejsca#index'

  match "login" => "sessions#new"
  match "loguj" => "sessions#new"
  match "wyloguj" => "sessions#destroy"

  match 'reset_hasla' => 'osoby#reset_hasla', :via => :get
  match 'reset_hasla' => 'osoby#zresetuj_haslo', :via => :post
  match 'ustaw_haslo' => 'osoby#ustaw_haslo', :via => :get
 

  scope(:path_names=>{:new=>"nowa", :edit=>"edytuj"}) do
    resources :grupy, :osoby, :aktualnosci
    resources :sessions, :path=>"sesje"
  end

end

app/controllers/osoby_controller.rb
class OsobyController < ApplicationController
  load_and_authorize_resource
  # GET /osoby
  # GET /osoby.json
  def index
    @osoby = Osoba.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @osoby }
    end
  end

  # GET /osoby/1
  # GET /osoby/1.json
  def show
    @osoba = Osoba.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @osoba }
    end
  end

  # GET /osoby/new
  # GET /osoby/new.json
  def new
    @osoba = Osoba.new
    @osoba.generuj_tymczasowe_haslo
    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @osoba }
    end
  end

  # GET /osoby/1/edit
  def edit
    @osoba = Osoba.find(params[:id])
  end

  # POST /osoby
  # POST /osoby.json
  def create
    @osoba = Osoba.new(params[:osoba])

    respond_to do |format|
      if @osoba.save        
        
        format.html { redirect_to @osoba, notice: t(:created_notice, :model=>Osoba) }
        #format.json { render json: @osoba, status: :created, location: @osoba }
      else
        format.html { render action: "new" }
        #format.json { render json: @osoba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /osoby/1
  # PUT /osoby/1.json
  def update
    @osoba = Osoba.find(params[:id])

    respond_to do |format|
      if @osoba.update_attributes(params[:osoba])
        format.html { redirect_to @osoba, notice: t(:updated_notice, :model=>t('activerecord.models.osoba')) }
        #format.json { head :no_content }
      else
        format.html { render action: "edit" }
        #format.json { render json: @osoba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /osoby/1
  # DELETE /osoby/1.json
  def destroy
    @osoba = Osoba.find(params[:id])
    @osoba.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      #format.json { head :no_content }
    end
  end

  # GET /reset_hasla
  def reset_hasla
    
  end

  # POST /reset_hasla
  def zresetuj_haslo
    @osoba = Osoba.find_by_email(params[:email])
    if @osoba
      @osoba.generuj_tymczasowe_haslo
      @osoba.save!
      OsobaMailer.haslo(@osoba, root_url).deliver
      redirect_to login_path, notice: t(:updated_notice, :model=>t('activerecord.attributes.osoba.password'))
    else
      redirect_to login_path, notice: t(:not_found, :model=>t('activerecord.models.osoba'))
    end
  end

  # GET /ustaw_haslo
  def ustaw_haslo
    @osoba = Osoba.find(params[:id])
    if @osoba
      @osoba.wyczysc_tymczasowe_haslo      
    else
      redirect_to root_path, notice: t(:not_found, :model=>t('activerecord.models.osoba'))
    end
  end


  def wyslij_newsletter
    NewsletterMailer.welcome_email(Osoba.where(:email=>"jerzy.czepiel@gmail.com").first).deliver
  end
end

app/views/osoby/_form.html.erb
<%= form_for(@osoba) do |f| %>
  <% if @osoba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@osoba.errors.count, t(:error)) %> </h2>

      <ul>
      <% @osoba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :nazwisko%><br />    
    <%= f.text_field :nazwisko %>    
  </div>
  <div class="field">
    <%= f.label :email%><br />
    <%if defined?(disabled)%>
      <%= f.text_field :email, :disabled=>'disabled' %>
    <%else%>
      <%= f.text_field :email %>
    <%end%>

  </div>

  <div class="inlet_text">
    <%=t(:temporary_password)%>
  </div>

  <div class="field">
    <%= f.label :tymczasowe_haslo%><br />
    <%= f.text_field :tymczasowe_haslo %>
  </div>

  <div class="field">
    <%=f.label :grupy%>
    <% for g in Grupa.all %>
      <div class="check_box"><%= check_box_tag "osoba[grupa_ids][]", g.id, @osoba.grupy.include?(g) %>
      <%=h g.nazwa %></div><br />
    <% end %>
  </div>

  <%if @osoba.avatar%>
    <div class="foto">
      <%= image_tag @osoba.avatar.url(:medium) %>
    </div>
  <%end%>

  <div class="field">
    <%= f.label :avatar%>
    <%= f.file_field :avatar %>
  </div>



  <div class="field">
    <%= f.label :stanowisko%><br />
    <%= f.text_field :stanowisko %>
  </div>

  <div class="actions">
    <%= f.button t(:save), :class=>'btn btn-success' %>
  </div>
<% end %>

app/views/osoby/_form_rejestracja.html.erb
<%= form_for(@osoba) do |f| %>
  <% if @osoba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@osoba.errors.count, "błąd") %> </h2>

      <ul>
      <% @osoba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :nazwisko%><br />
    <%= f.text_field :nazwisko %>
  </div>

  <div class="field">
    <%= f.label :email%><br />
    <%if defined?(disabled)%>
      <%= f.text_field :email, :disabled=>'disabled' %>
    <%else%>
      <%= f.text_field :email %>
    <%end%>
  </div>
  <div class="field">
    <%= f.label :password%><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation%><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <%unless defined? disabled%>
  <div class="field">
    <%= f.label :grupy%>
    <%= select_tag("grupy[]", options_for_select(Grupa.order(:nazwa).map{|m| [m.nazwa,m.id]}, @osoba.grupy.collect{ |s| s.id }),
                   {:multiple=>true, :id => "grupy"}) %>
  </div>
  <%end%>

  <%if @osoba.avatar%>
    <div class="foto">
      <%= image_tag @osoba.avatar.url(:medium) %>
    </div>
  <%end%>

  <div class="field">
    <%= f.label :avatar%>
    <%= f.file_field :avatar %>
  </div>

 

 

  <div class="field">
    <%= f.label :stanowisko%><br />
    <%= f.text_field :stanowisko %>
  </div>
  <div class="actions">
    <%= f.submit t(:save), :class=>'red_button' %>
  </div>
<% end %>

app/views/osoby/_wizytowka.html.erb
<article class="wizytowka">
  <header>
    <div class="foto">
      <%= image_tag wizytowka.avatar.url(:medium) %>
    </div>
   
  </header>
  <section>
    <div class="nazwisko">
      <%= link_to "#{wizytowka.nazwisko}",wizytowka %>
    </div>
    <h5><%=wizytowka.email%></h5>

  </section>
  <div class="buttony">

    <%if admin?%>
      |<%= link_to t(:show), wizytowka %> |
      <%= link_to t(:edit), edit_osoba_path(wizytowka) if can? :update, wizytowka%> |
      <%= link_to t(:delete), wizytowka, method: :delete, data: { confirm: t(:confirm) } if can? :delete, wizytowka%>
    <%end%>
  </div>
  <div class="clear"></div>
</article>

app/views/osoby/_wizytowka_do_newslettera.html.erb
<div class="wizytowka" style="clear: both;background: none repeat scroll 0 0 #FFFFFF;border: 1px solid black;box-shadow: 3px 3px 7px -1px #000000;margin: 10px 0;width: 600px;">
  <div class="header" style="float: left;padding: 5px;text-align: center;width: 110px;">
    <div class="foto">
      <%= image_tag wizytowka_do_newslettera.avatar.url(:medium) %>
    </div>
    <div class="nazwisko">
      <%= link_to "#{wizytowka_do_newslettera.nazwisko}",wizytowka_do_newslettera%>
    </div>
  </div>
  <div class="section" style="float: right;width: 475px;">
    <h5><%wizytowka_do_newslettera.email%></h5>
    <br /> <%= wizytowka_do_newslettera.instytucja %>
    <br /> <%= wizytowka_do_newslettera.opis %>
  </div>
</div>

app/views/osoby/_wizytowka_mala.html.erb
<article class="wizytowka_mala">
  <header class="left">
    <div class="foto">
      <%= image_tag wizytowka_mala.avatar.url(:thumb) %>
    </div>
  </header>
  <section class="left">
    <div class="nazwisko">
      <%= link_to "#{wizytowka_mala.nazwisko}",wizytowka_mala %>
    </div>
  </section>
  <div class="clear"></div>
</article>

app/views/osoby/_wizytowka_small.html.erb
      <%= link_to "#{wizytowka_small.nazwisko}",wizytowka_small %>

app/views/osoby/edit.html.erb
<h1><%=t(:edit_osoba)%></h1>


  <%unless "#{current_user.try(:id)}" == params[:id]%>
  <%= render 'form' %>
  <%else%>
  <%= render 'form_rejestracja', :disabled=>true %>
  <%end%>


<%= link_to t(:back), osoby_path %>

app/views/osoby/index.html.erb
<h1><%=Osoba.model_name.human.pluralize%></h1>
<div class="button_dodaj">
  <%= link_to t(:new), new_osoba_path, :class=>'btn btn-success' if can? :create, Osoba%>
</div>
<br />

<%#= render :partial=>"osoby/wizytowka",:collection=>@osoby %>

<table  class="table table-striped">
  <tr>
    <th>Nazwisko</th>
    <th>email</th>

    <th></th>
    <th></th>
  </tr>

<% @osoby.each do |o| %>
  <tr>
    <td><%= link_to o.nazwisko,o %></td>
    <td><%= o.email %></td>



    <td><%= link_to 'Edit', edit_osoba_path(o) ,:class=>'btn btn-success'%></td>
    <td><%= link_to t(:delete), o, method: :delete, data: { confirm: t(:confirm) } ,:class=>"btn btn-warning" if can? :delete,o%></td>

  </tr>
<% end %>
</table>

app/views/osoby/new.html.erb
<h1>Nowa osoba</h1>

<%= render 'form' %>

<%= link_to t(:back), osoby_path %>

app/views/osoby/reset_hasla.html.erb
<%=t(:reset_hasla)%>
<%=form_tag reset_hasla_path do%>
  <div class="field">
  	<%=label_tag t 'activerecord.attributes.osoba.email'%>
  	<%=text_field_tag :email, params[:email], {:id=>'email2'}%>
  </div>
  <div class="actions"><%=submit_tag t :ustaw_haslo%></div>
<%end%>

app/views/osoby/show.html.erb
<%= render :partial=>"osoby/wizytowka",:object=>@osoba %>

app/views/osoby/ustaw_haslo.html.erb
<%= form_for(@osoba) do |f| %>
  <% if @osoba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@osoba.errors.count, "error") %> </h2>

      <ul>
      <% @osoba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password%><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation%><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.hidden_field :tymczasowe_haslo %>

  <div class="actions">
    <%= f.submit t(:save) %>
  </div>
<% end %>

app/views/osoby/wyslij_newsletter.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "wyslij_newsletter.html" %>