config/routes.rb
Msza::Application.routes.draw do

  resources :terminy

  resources :kraje

  resources :miejsca

  resources :osoby

  root :to => 'miejsca#index'

  match "login" => "sessions#new"
  match "loguj" => "sessions#new"
  match "wyloguj" => "sessions#destroy"

  match 'reset_hasla' => 'osoby#reset_hasla', :via => :get
  match 'reset_hasla' => 'osoby#zresetuj_haslo', :via => :post
  match 'ustaw_haslo' => 'osoby#ustaw_haslo', :via => :get
 

  scope(:path_names=>{:new=>"nowa", :edit=>"edytuj"}) do
    resources :grupy, :osoby, :aktualnosci
    resources :sessions, :path=>"sesje"
  end

end

app/views/layouts/_dni.html.erb
<div class="row">
<%id = (defined? id) ? id : ''%>
<div class="span">
	<h4>Wybierz dzień:</h4>
</div>
<div class="span3">
<ul class="nav nav-pills ">
	<li class="<%="active" unless params[:dzien]%>">
		<%=link_to "Wszystkie dni",{:controller=>kontroler,:action=>akcja,:id=>id},:class=>""%>
	</li>
	<li class="<%="active" if Dzien.dzisiaj==params[:dzien].try(:to_i)%>">	
		<%=link_to "Dzisiaj",{:controller=>kontroler,:action=>akcja,:id=>id,:dzien=>Dzien.dzisiaj},:class=>""%>
	</li>
	<li class="<%="active" if Dzien.jutro==params[:dzien].try(:to_i)%>">
		<%=link_to "Jutro",{:controller=>kontroler,:action=>akcja,:id=>id,:dzien=>Dzien.jutro},:class=>""%>
	</li>
</ul>	
</div>
<div class="span5">
<ul class="nav nav-pills">
<%Dzien.order(:id).each do |d|%>
	<li class="<%="active" if d.id==params[:dzien].try(:to_i)%>">
  <%=link_to "#{d.nazwa}",{:controller=>kontroler,:action=>akcja,:id=>id,:dzien=>d.id},:class=>""%>
  </li>
<%end%>

</ul>
</div>
</div>

<%= render "miejsca/statystyki" %>

app/views/layouts/_menu.html.erb
ul>
  <li><a href="#home" class="active">Witamy<br /><span>na CC-Net.pl </span></a></li>
  <li><a href="#portfolio">Portfolio<br /><span>Zrealizowane projekty</span></a></li>
  <li><a href="#oferta">Oferta<br /><span>Nasze produkty</span></a></li>
  <li><a href="#kontakt">Kontakt<br /><span>Napisz do nas</span></a></li>
</ul>

app/views/layouts/_menu_nasze.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Msza Trydencka na świecie</a>

      <ul class="nav">
     
        <%if current_user.try(:admin?)%>
          <li><%=link_to "Użytkownicy", osoby_path %></li>
        <%end%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Odprawiające grupy
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <%if current_user.try(:admin?)%>
              <li><%=link_to "Grupy", grupy_path %></li>
            <%end%>
            <%Grupa.where("nazwa <> 'Administratorzy'").each do |g|%>
              <li><%=link_to g.nazwa, g %></li>
            <%end%>
          </ul>
        </li>

        <%if current_user%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Mój Profil
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to current_user.nazwisko, current_user %> </li>

              <li><%= link_to "Edytuj mój profil",edit_osoba_path(current_user) %> </li>
              <li><%=link_to t(:logout), wyloguj_path%></li>
            </ul>
          </li>
        <%else%>
          <li><%=link_to t(:login), loguj_path%></li>
        <%end%>
      </ul>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=t(:tytul)%></title>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery-1.7.1.min"%>
  <%= javascript_include_tag "bootstrap.min" %>
  <%= stylesheet_link_tag "gmaps4rails"%>
  <%= stylesheet_link_tag "bootstrap.min", :media => "all" %>
  <%= stylesheet_link_tag "bootstrap-responsive.min", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render :partial=>"layouts/menu_nasze" %>
  <div class="container" style="margin-top:40px">


  <%=yield%>



    </div>
<%= yield :scripts %>
</body>
</html>